spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
  datasource:
    url: jdbc:mysql://156.67.72.101:3306/u117615979_tienda
    driverClassName: com.mysql.cj.jdbc.Driver
    username: u117615979_tienda_user
    password: Software_Architecture2023#
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081