spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
    listener:
      direct:
        retry:
          max-attempts: 3
          enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
